USE bank_lab_cycle_2;
SELECT CNAME FROM DEPOSIT where cname not in(SELECT CNAME FROM  BORROW);
select cname from deposit where cname in (select cname from borrow);
SELECT D1.CNAME FROM DEPOSIT D1 WHERE D1.BNAME IN(SELECT D2.BNAME FROM DEPOSIT D2 WHERE D2.CNAME = 'SUNIL' );
SELECT C1.CNAME FROM CUSTOMER C1,DEPOSIT D1, BRANCH B1 WHERE C1.CITY ='NAGPUR' AND C1.CNAME = D1.CNAME AND D1.BNAME = B1.BNAME AND B1.CITY IN('BOMBAY','DELHI');
SELECT Distinct(CUSTOMER.CNAME) from CUSTOMER,DEPOSIT WHERE City='NAGPUR';
SELECT C1.CNAME FROM CUSTOMER C1,DEPOSIT D1, BRANCH B1 WHERE C1.CITY = 'NAGPUR' AND C1.CNAME = D1.CNAME AND D1.BNAME= B1.BNAME AND B1.CITY IN ('BOMBAY');
SELECT B1.CITY FROM DEPOSIT D1, BRANCH B1 WHERE D1.BNAME = B1.BNAME AND D1.CNAME IN ('SUNIL' ,'ANIL');